commit-message: "Global commit message"  # Optional, defaults to "Sync GitHub files"
entries:
  - commit-message: "Sync README" # Optionally, Overwrites the global commit message
    from: # Copies from The repo Knerio/Knerio the file README.md
      repo: "Knerio/Knerio"
      file: "README.md"
    to: # Pastes as README.md (can also be renamed) in Knerio/GithubSyncFilesAction
      repo: "Knerio/GithubSyncFilesAction"
      file: "showcase/README.md"

  - from:
      repo: "Knerio/Knerio"
      file: ".github/" # You can also copy a whole directory
    to:
      repo: "Knerio/GithubSyncFilesAction"
      file: "showcase/second/"