---
global-commit-message: "Global commit message"  # Optional, defaults to "Sync GitHub files"
entries:
  - commit-message: "Sync README" # Optionally, Overwrites the global commit message
    from:
      repo: "Knerio/Knerio"
      file: "README.md"
    to:
      repo: "Knerio/GithubSyncFilesAction"
      file: "showcase/README.md"
  - from:
      repo: "Knerio/Knerio"
      file: "README.md"
    to:
      repo: "Knerio/GithubSyncFilesAction"
      file: "showcase/second/README.md"

